name: PlatformIO Build Test

on:
  push:
    branches:
      - main
      - dev
      - auto-build
  pull_request:
    branches:
      - main
      - dev
      - auto-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build Examples
        run: |
          examples=$(find examples -name "platformio.ini")
          for exampleConf in $examples; do
            echo "Building example with configuration: $exampleConf"
            platformio ci --project-conf="$exampleConf" --lib="."
          done
