name: Package Arduino Library and Submit PR

on:
  push:
    branches: [main, feature-63/auto-build-arduino]

jobs:
  build_package:
    runs-on: ubuntu-latest # Runner environment

    steps:
      # Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Checkout the motorgo-arduino repository
      - name: Checkout motorgo-arduino Repository
        uses: actions/checkout@v4
        with:
          repository: Every-Flavor-Robotics/motorgo-arduino
          path: motorgo-arduino

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: pip install click platformio

      # Run your packaging script
      - name: Build Arduino Package
        env:
          REPO_NAME: ${{ github.repository }} # Set environment variable
        run: |
          python .github/scripts/package_arduino_lib.py library.json motorgo-mini-driver \
            --output-dir $GITHUB_WORKSPACE/motorgo-arduino/arduino_library \
            --storage-dir ./tmp

      # Stage Package Files
      # - name: Stage and Commit Package Files
      #   run: |
      #     cd $GITHUB_WORKSPACE/motorgo-arduino  # Move into the 'motorgo-arduino' directory

      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.MOTORGO_ARD_DEPLOY_KEY }}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa  # Set secure permissions
      #     git remote set-url origin git@github.com:Every-Flavor-Robotics/motorgo-arduino.git # Use Git's SSH URL

      #     # Branch Creation (Adjust naming logic as needed)
      #     # Branch name should be tied to commit hash
      #     branch_name="auto-package-update/$GITHUB_SHA"
      #     git checkout -b $branch_name

      #     git add -A  # Stage all changes
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git commit -m "Automated Arduino library package update"
      #     git push origin $branch_name  # Push the new branch

      # # Open Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.MOTORGO_ARDUINO_KEY }}
          # /$GITHUB_WORKSPACE/motorgo-arduino
          path: /${{ github.workspace }}/motorgo-arduino
          commit-message: Automated Arduino Package Update
          branch: auto-package-update/${{ github.sha }}
          title: Arduino Library Update to ${{ github.sha }}
          body: |
            Automated update of the Arduino library package
            Please review changes.
          base: main # The branch to open the PR against
