name: Build and Publish Documentation (Pushes)

on:
  pull_request:
    branches:
      - dev
      - main
    # types: [closed]
  push:
    branches:
      - bug-94/fix-multiversion

jobs:
  build-and-deploy-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          pip install sphinx breathe exhale sphinx_rtd_theme sphinxcontrib-versioning sphinx-multiversion

      - name: Build Documentation
        run: |
          cd docs
          sphinx-multiversion . _build/html -D 'exhale_args.containmentFolder=${sourcedir}/api'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
