name: Build and Publish Documentation (Pushes)

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          pip install sphinx breathe exhale sphinx_rtd_theme sphinxcontrib-versioning sphinx-multiversion

      - name: Build Documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html/${{ github.ref_name }}  # Version matches branch

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
