name: Build Documentation (PR Validation)

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-docs:
    permissions:
      contents: read  # Only needs read permissions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          pip install sphinx breathe exhale sphinx_rtd_theme sphinxcontrib-versioning sphinx-multiversion

      - name: Build Documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html
